name: CLDF-validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycldf
    - name: Test with pytest
      run: |
        cldf validate vonprincedaakaka/cldf/Dictionary-metadata.json
        cldf validate vonprincedaakaka/cldf/cldf-metadata.json
        cldf validate hydeamahuaca/cldf/Dictionary-metadata.json
        cldf validate hydeamahuaca/cldf/cldf-metadata.json
