name: CLDF-validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cldf
    - name: Validate CLDF datasets using pytest
      run: |
        pytest --cldf-metadata=vonprincedaakaka/cldf/Dictionary-metadata.json test.py
        pytest --cldf-metadata=vonprincedaakaka/cldf/cldf-metadata.json test.py
        pytest --cldf-metadata=hydeamahuaca/cldf/Dictionary-metadata.json test.py
        pytest --cldf-metadata=hydeamahuaca/cldf/cldf-metadata.json test.py
